#!/bin/sh
# Xsetup - run as root before the login dialog appears
# Place in /usr/share/sddm/scripts

xrandr --output DP-1-1 --mode "2560x1440" --rate 100
xrandr --output DP-1-2 --mode "1920x1080" --left-of DP-1-1 --rate 144
xrandr --output DP-1-3 --mode "1920x1080" --right-of DP-1-1 --rate 60
